-- ================================================================
-- SAT Practice Test A (Full-Length) — 98 original questions
-- ================================================================
-- Paste into Supabase SQL Editor and click Run.
-- Creates one published test (27 RW1 + 27 RW2 + 22 Math1 + 22 Math2)
-- with topics, difficulty curve, and explanations, and assigns it
-- to every existing student profile.
-- Safe to re-run: skips if the test already exists.
-- All questions are original content written for this platform.
-- ================================================================

do $$
declare
  v_test_id uuid;
begin
  if exists (select 1 from public.tests where name = 'SAT Practice Test A (Full-Length)') then
    raise notice 'SAT Practice Test A already exists - skipping.';
    return;
  end if;

  insert into public.tests (name, status, rw_minutes, math_minutes, break_minutes)
  values ('SAT Practice Test A (Full-Length)', 'published', 64, 70, 10)
  returning id into v_test_id;

  -- ==============================================================
  -- READING & WRITING — MODULE 1 (27 questions, order 0-26)
  -- ==============================================================
  insert into public.questions (test_id, section, module_key, difficulty, topic, stem, choices, correct, order_num, explanation) values
  (v_test_id,'rw','rw1','easy','craft and structure',
   'The community center''s new reading room was designed to be ______ to visitors of all ages: adjustable desks, large-print books, and audio stations invite everyone to take part. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('indifferent','accessible','identical','resistant'),1,0,
   'The colon introduces features that make the room usable by everyone, so "accessible" is the most precise choice.'),
  (v_test_id,'rw','rw1','easy','expression of ideas',
   'Maria practiced the violin for at least an hour every day for a year. ______ her performance at the spring recital was nearly flawless. Which choice completes the text with the most logical transition?',
   jsonb_build_array('However,','As a result,','For instance,','In contrast,'),1,1,
   'The flawless performance is the effect of daily practice, so the cause-and-effect transition "As a result" fits.'),
  (v_test_id,'rw','rw1','easy','standard english conventions',
   'The collection of rare stamps ______ on display at the public library this month. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('are','were','is','have been'),2,2,
   'The subject is the singular noun "collection," so the singular verb "is" agrees with it.'),
  (v_test_id,'rw','rw1','easy','information and ideas',
   'When a honeybee finds a rich patch of flowers, it returns to the hive and performs a repetitive movement known as a waggle dance. The angle of the dance communicates the direction of the flowers relative to the sun, and the length of the dance signals the distance. Hivemates that watch the dance can then fly directly to the food source. Which choice best states the main idea of the text?',
   jsonb_build_array('Honeybees prefer flowers that grow close to their hives.','Honeybees use a specialized dance to share the location of food with other bees.','Honeybees rely on the sun for warmth while foraging.','Honeybees compete with hivemates for access to flowers.'),1,3,
   'Every sentence explains how the waggle dance communicates the location of food to other bees.'),
  (v_test_id,'rw','rw1','easy','standard english conventions',
   'Nadia packed three essentials for the overnight ______ a map, a headlamp, and a water filter. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('hike:','hike;','hike,','hike'),0,4,
   'A colon after an independent clause correctly introduces the list of items.'),
  (v_test_id,'rw','rw1','easy','craft and structure',
   'Because the DNA evidence was ______, the jury needed little deliberation before reaching its verdict. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('ambiguous','conclusive','irrelevant','fabricated'),1,5,
   'Evidence that settles a question quickly is "conclusive"; the other choices would make deliberation harder, not easier.'),
  (v_test_id,'rw','rw1','easy','standard english conventions',
   'The planning committee released ______ final recommendations at the town meeting on Tuesday. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('it''s','their','its','there'),2,6,
   '"Committee" is singular, and the possessive form is "its" (no apostrophe).'),
  (v_test_id,'rw','rw1','easy','information and ideas',
   'Most cacti store water in their thick, fleshy stems. The night-blooming cereus, however, has a thin, twiggy stem and instead survives long dry periods by drawing on a large, water-storing root below the ground. Based on the text, it can most reasonably be inferred that the night-blooming cereus ______',
   jsonb_build_array('stores water in a different part of the plant than most cacti do.','requires more frequent rainfall than most cacti do.','blooms only when its stem is full of water.','has a thicker stem than most other cacti.'),0,7,
   'The contrast ("however... instead") shows it uses a root, not a stem, unlike most cacti.'),
  (v_test_id,'rw','rw1','easy','expression of ideas',
   'The recipe for the bread looked simple, calling for only four ingredients. ______ it demanded several techniques that took the baker weeks to master. Which choice completes the text with the most logical transition?',
   jsonb_build_array('Therefore,','Similarly,','Nevertheless,','In other words,'),2,8,
   'The second sentence contrasts with the apparent simplicity, so the contrast transition "Nevertheless" is logical.'),
  (v_test_id,'rw','rw1','medium','craft and structure',
   'The economist''s 2010 forecasts proved remarkably ______: nearly every trend she identified had emerged by the end of the decade. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('prescient','tentative','erroneous','conventional'),0,9,
   '"Prescient" means showing accurate foresight, which matches predictions that later came true.'),
  (v_test_id,'rw','rw1','medium','craft and structure',
   'In her memoir, novelist Amara Okafor describes rewriting the opening chapter of her first book seventeen times, reading each draft aloud and cutting any sentence whose rhythm felt wrong. Which choice best describes the function of this detail in the memoir?',
   jsonb_build_array('It illustrates Okafor''s meticulous approach to revising her prose.','It suggests that Okafor regretted publishing her first book.','It shows that Okafor preferred writing later chapters first.','It demonstrates that reading aloud is unnecessary for most writers.'),0,10,
   'Seventeen rewrites and sentence-by-sentence cuts illustrate extreme care in revision.'),
  (v_test_id,'rw','rw1','medium','standard english conventions',
   'By the time the hurricane reached the coastline, most residents ______ their windows and moved inland. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('board','had boarded','will board','are boarding'),1,11,
   'The past perfect "had boarded" shows an action completed before another past event.'),
  (v_test_id,'rw','rw1','medium','information and ideas',
   'Urban ecologists hypothesize that community gardens lower summer air temperatures in the surrounding blocks. Which finding, if true, would most directly support this hypothesis?',
   jsonb_build_array('Blocks adjacent to community gardens averaged air temperatures 2 degrees Celsius lower than otherwise similar blocks without gardens.','Community gardens are most often planted in neighborhoods with older housing.','Volunteers who work in community gardens report enjoying cooler evenings.','Blocks with gardens and blocks without gardens recorded identical summer temperatures.'),0,12,
   'A measured temperature difference between comparable blocks with and without gardens directly supports the hypothesis.'),
  (v_test_id,'rw','rw1','medium','standard english conventions',
   'Examining the fragile manuscript under ultraviolet light, ______. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('faint notes appeared in the margins to the archivist','the margins revealed faint notes to the archivist','the archivist noticed faint notes in the margins','there were faint notes in the margins'),2,13,
   'The person doing the examining (the archivist) must directly follow the introductory modifier.'),
  (v_test_id,'rw','rw1','medium','expression of ideas',
   'Over the past decade, the price of solar panels has fallen by more than half. ______ the cost of wind turbines has dropped sharply, making renewable energy increasingly competitive. Which choice completes the text with the most logical transition?',
   jsonb_build_array('Similarly,','However,','Instead,','Consequently,'),0,14,
   'Both sentences describe parallel price declines, so the comparison transition "Similarly" fits.'),
  (v_test_id,'rw','rw1','medium','craft and structure',
   'The two witnesses offered ______ accounts of the accident, and investigators spent weeks trying to reconcile the differences. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('identical','conflicting','thorough','reliable'),1,15,
   'Accounts with "differences" that must be reconciled are "conflicting."'),
  (v_test_id,'rw','rw1','medium','craft and structure',
   'A text first describes the shrinking habitat of the monarch butterfly, then outlines two conservation programs, and finally evaluates the early results of each program. Which choice best describes the overall structure of the text?',
   jsonb_build_array('It presents a problem and then examines possible responses to that problem.','It compares two species and then explains their shared traits.','It narrates a historical event in chronological order.','It states a theory and then rejects it entirely.'),0,16,
   'Habitat loss is the problem; the programs and their results are the responses examined.'),
  (v_test_id,'rw','rw1','medium','standard english conventions',
   'The lighthouse ______ still guides ships into the harbor. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('which was built in 1854,',', which was built in 1854,',', which was built in 1854','which was built in 1854'),1,17,
   'A nonrestrictive clause must be set off by commas on both sides.'),
  (v_test_id,'rw','rw1','hard','craft and structure',
   'Although the senator''s remarks appeared improvised, aides later revealed that every pause and gesture had been carefully ______ weeks in advance. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('orchestrated','abandoned','improvised','misconstrued'),0,18,
   '"Orchestrated" (carefully planned) contrasts with the appearance of improvisation.'),
  (v_test_id,'rw','rw1','hard','information and ideas',
   'Radiocarbon dating can determine the age of organic material up to about 50,000 years old, but the technique requires destroying a small sample of the artifact. Museum curators are often unwilling to permit such destruction of rare objects. As a result, researchers have increasingly turned to ______',
   jsonb_build_array('methods that can estimate an artifact''s age without damaging it.','artifacts that are less than 50,000 years old.','museums that own large collections of duplicate objects.','techniques that destroy larger samples but give faster results.'),0,19,
   'If destruction is the obstacle, the logical response is nondestructive dating methods.'),
  (v_test_id,'rw','rw1','hard','standard english conventions',
   'The experiment produced a puzzling ______ the bacteria thrived in conditions that should have killed them. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('result,','result;','result','result and'),1,20,
   'Two independent clauses must be joined by a semicolon; a comma alone creates a comma splice.'),
  (v_test_id,'rw','rw1','hard','expression of ideas',
   'While researching a topic, a student has taken the following notes: The Great Green Wall is an African-led project launched in 2007. Its goal is to grow an 8,000-kilometer band of trees and grassland across the Sahel. By 2023, about 18 percent of the target area had been restored. Restored land has already created jobs in Senegal and Ethiopia. The student wants to emphasize the project''s progress so far. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
   jsonb_build_array('Launched in 2007, the Great Green Wall aims to cross the entire Sahel.','By 2023, the Great Green Wall project had restored about 18 percent of its target area and created jobs in Senegal and Ethiopia.','The Great Green Wall is an African-led project with an 8,000-kilometer goal.','Some of the Great Green Wall''s restored land lies in Senegal.'),1,21,
   'Only this choice cites concrete accomplishments (18 percent restored, jobs created), emphasizing progress.'),
  (v_test_id,'rw','rw1','hard','information and ideas',
   'Bioluminescent organisms produce light through a chemical reaction between luciferin and oxygen. Deep-sea fish use this light to lure prey, fireflies use it to attract mates, and some fungi may use it to draw insects that spread their spores. The main purpose of the text is to ______',
   jsonb_build_array('describe the varied functions that bioluminescence serves across different organisms.','argue that bioluminescence evolved first in deep-sea fish.','explain why fireflies are more efficient light producers than fungi.','question whether fungi are truly bioluminescent.'),0,22,
   'The text lists three different organisms and the different purposes their light serves.'),
  (v_test_id,'rw','rw1','hard','standard english conventions',
   'The results of the ten-year study on adolescent sleep patterns ______ that later school start times improve both attendance and grades. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('suggests','suggest','is suggesting','has suggested'),1,23,
   'The plural subject "results" requires the plural verb "suggest"; the intervening phrase does not change agreement.'),
  (v_test_id,'rw','rw1','hard','craft and structure',
   'The critic''s review was so ______ that even the film''s director conceded its fairness: it praised the movie''s strengths and cataloged its flaws with equal care. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('scathing','evenhanded','effusive','dismissive'),1,24,
   'A review that treats strengths and flaws with equal care is balanced, or "evenhanded."'),
  (v_test_id,'rw','rw1','hard','information and ideas',
   'A team of researchers claims that a newly discovered footprint fossil proves that early humans reached the island at least 20,000 years ago. Which finding, if true, would most directly weaken the researchers'' claim?',
   jsonb_build_array('Sediment tests show the layer containing the footprint is only 6,000 years old.','Other footprints of the same size were found on a nearby island.','The footprint is slightly smaller than the average modern human foot.','Stone tools found elsewhere on the island are 25,000 years old.'),0,25,
   'If the sediment layer is only 6,000 years old, the footprint cannot support a 20,000-year-old arrival.'),
  (v_test_id,'rw','rw1','hard','expression of ideas',
   'Critics predicted the electric delivery vans would fail within a year. ______ the fleet has now logged five years of service with lower maintenance costs than the diesel vans it replaced. Which choice completes the text with the most logical transition?',
   jsonb_build_array('Accordingly,','Instead,','Likewise,','Specifically,'),1,26,
   'The outcome contradicts the prediction, so "Instead" signals the reversal.');

  -- ==============================================================
  -- READING & WRITING — MODULE 2 (27 questions, order 27-53)
  -- ==============================================================
  insert into public.questions (test_id, section, module_key, difficulty, topic, stem, choices, correct, order_num, explanation) values
  (v_test_id,'rw','rw2','easy','craft and structure',
   'The assembly instructions were so ______ that first-time customers finished building the bookshelf in under ten minutes. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('vague','straightforward','lengthy','technical'),1,27,
   'Instructions that let beginners finish quickly are clear, or "straightforward."'),
  (v_test_id,'rw','rw2','easy','expression of ideas',
   'The trail to the summit was steep, rocky, and poorly marked. ______ every member of the group reached the top before noon. Which choice completes the text with the most logical transition?',
   jsonb_build_array('Nevertheless,','Therefore,','For example,','Meanwhile,'),0,28,
   'Success despite the difficult trail calls for the contrast transition "Nevertheless."'),
  (v_test_id,'rw','rw2','easy','standard english conventions',
   'After six hours of continuous printing, the machine finally completed ______ largest job of the week. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('it''s','its','their','there'),1,29,
   'The possessive of "it" is "its"; "it''s" means "it is."'),
  (v_test_id,'rw','rw2','easy','information and ideas',
   'In the 1990s, the city of Philadelphia began commissioning large murals on the walls of vacant buildings. Residents helped choose the subjects, local artists led the painting, and neighbors gathered at unveiling ceremonies. Surveys later found that many residents felt the murals gave their blocks a stronger sense of identity. Which choice best states the main idea of the text?',
   jsonb_build_array('Philadelphia''s mural program involved residents and strengthened neighborhood identity.','Vacant buildings are common in most large American cities.','Professional artists rarely collaborate with local residents.','Murals are less expensive than other forms of public art.'),0,30,
   'The text describes resident involvement and the resulting sense of identity; the other choices are unsupported.'),
  (v_test_id,'rw','rw2','easy','standard english conventions',
   'There ______ several strong reasons to expand the after-school tutoring program. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('is','was','are','has been'),2,31,
   'The true subject is the plural "reasons," so the plural verb "are" is required.'),
  (v_test_id,'rw','rw2','easy','craft and structure',
   'The volunteers sorted donations with such ______ that the food drive finished a full week ahead of schedule. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('hesitation','efficiency','reluctance','difficulty'),1,32,
   'Finishing early implies the work was done with "efficiency."'),
  (v_test_id,'rw','rw2','easy','standard english conventions',
   'The chef''s signature dish combines roasted ______ and a lemon dressing. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('peppers, toasted almonds,','peppers toasted almonds,','peppers, toasted almonds','peppers; toasted almonds;'),0,33,
   'Items in a series are separated by commas: "roasted peppers, toasted almonds, and a lemon dressing."'),
  (v_test_id,'rw','rw2','easy','information and ideas',
   'Sea otters wrap themselves in strands of kelp before sleeping. The kelp is anchored to the seafloor, and wrapped otters stay in place even as currents move through the water. Based on the text, it can most reasonably be inferred that the otters use the kelp to ______',
   jsonb_build_array('avoid drifting away while they sleep.','hide from predators hunting at night.','keep warm in cold water.','attract small fish to eat upon waking.'),0,34,
   'The anchored kelp keeps otters "in place" against currents, so it prevents drifting during sleep.'),
  (v_test_id,'rw','rw2','easy','craft and structure',
   'In an article encouraging small lifestyle changes, the author notes that a single reusable bottle can replace hundreds of disposable ones each year. The author most likely includes this detail to ______',
   jsonb_build_array('emphasize the large impact of a simple change in habit.','criticize companies that manufacture disposable bottles.','suggest that reusable bottles are too expensive for most people.','describe the process by which bottles are recycled.'),0,35,
   'The statistic shows how one small habit produces a large effect, supporting the article''s theme.'),
  (v_test_id,'rw','rw2','medium','craft and structure',
   'Although initially ______ to share her preliminary data, the biologist eventually presented it at the conference after colleagues urged her to do so. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('eager','reluctant','unable','determined'),1,36,
   '"Although" and "eventually... after colleagues urged her" signal initial unwillingness, or reluctance.'),
  (v_test_id,'rw','rw2','medium','expression of ideas',
   'Many desert animals avoid the daytime heat. ______ the kangaroo rat spends daylight hours in a cool burrow and forages only after sunset. Which choice completes the text with the most logical transition?',
   jsonb_build_array('In contrast,','For example,','However,','As a result,'),1,37,
   'The kangaroo rat is a specific example of the general claim, so "For example" fits.'),
  (v_test_id,'rw','rw2','medium','standard english conventions',
   'The museum extended its evening ______ hundreds of visitors were still waiting when the doors finally closed. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('hours,','hours; however,','hours, however,','hours however,'),1,38,
   'Joining two independent clauses with "however" requires a semicolon before it and a comma after it.'),
  (v_test_id,'rw','rw2','medium','information and ideas',
   'Ornithologists hypothesize that city noise causes some songbirds to sing at higher pitches. Which finding, if true, would most directly support the hypothesis?',
   jsonb_build_array('Birds of the same species sing at higher pitches in loud urban districts than in quiet parks.','City birds sing more often in the early morning than forest birds do.','Songbirds in quiet forests use a wide range of pitches.','Traffic noise in most cities has increased steadily since 1990.'),0,39,
   'Comparing the same species across loud and quiet areas isolates noise as the relevant factor.'),
  (v_test_id,'rw','rw2','medium','standard english conventions',
   'Next spring, the observatory ______ its new telescope, the largest in the region. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('installed','had installed','will install','installs'),2,40,
   '"Next spring" places the action in the future, so "will install" is correct.'),
  (v_test_id,'rw','rw2','medium','craft and structure',
   'A passage opens with an anecdote about a failed bridge design, then explains the engineering principle the failure revealed, and closes by showing how modern bridges apply that principle. Which choice best describes the overall structure of the passage?',
   jsonb_build_array('A specific failure introduces a principle that is then applied broadly.','Two competing theories are presented and one is dismissed.','A chronological history of bridge building is offered.','An argument is made and then contradicted by new evidence.'),0,41,
   'The failure leads to a principle, which is then generalized to modern designs.'),
  (v_test_id,'rw','rw2','medium','craft and structure',
   'The mayor''s proposal received ______ support across party lines; council members from every faction praised it. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('broad','scant','reluctant','divided'),0,42,
   'Praise from every faction indicates wide-ranging, or "broad," support.'),
  (v_test_id,'rw','rw2','medium','expression of ideas',
   'A student researching the Danish island of Samso has taken these notes: In 1997 Samso won a national competition to become Denmark''s renewable energy island. Residents bought shares in new wind turbines. By 2007 the island produced more electricity from wind than it consumed. The student wants to emphasize how quickly the island reached its goal. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
   jsonb_build_array('Within a decade of winning a 1997 competition, Samso was producing more electricity from wind than it consumed.','Samso residents bought shares in new wind turbines.','Samso won a national renewable energy competition in 1997.','Denmark held a national renewable energy competition in the 1990s.'),0,43,
   'Only this choice connects the start date and the achievement to show the short time span.'),
  (v_test_id,'rw','rw2','medium','standard english conventions',
   'Hoping to reduce cafeteria waste, ______. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('compost bins were installed by the students.','the students installed compost bins near every exit.','compost bins near every exit were the students'' idea.','there were compost bins installed near every exit.'),1,44,
   'The introductory modifier must be followed by the people who were hoping: the students.'),
  (v_test_id,'rw','rw2','hard','craft and structure',
   'Fashions in slang are notoriously ______: expressions that dominate one year''s conversations often sound dated by the next. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('durable','ephemeral','obscure','universal'),1,45,
   '"Ephemeral" means short-lived, matching expressions that quickly go out of style.'),
  (v_test_id,'rw','rw2','hard','information and ideas',
   'Historians long assumed that the medieval fortress was purely defensive. Recent excavations, however, uncovered banquet halls, imported glassware, and decorative gardens within its walls. These findings most strongly suggest that the fortress ______',
   jsonb_build_array('also served as a residence meant to display wealth and status.','was abandoned shortly after its construction.','was less heavily fortified than historians once believed.','was built centuries later than previously thought.'),0,46,
   'Banquet halls, luxury goods, and gardens point to residential life and display, not just defense.'),
  (v_test_id,'rw','rw2','hard','standard english conventions',
   'Three cities submitted bids to host the ______ only one met every requirement in the charter. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('games','games,','games;','games, and,'),2,47,
   'Two independent clauses need a semicolon; a comma alone would create a comma splice.'),
  (v_test_id,'rw','rw2','hard','information and ideas',
   'A nutrition researcher argues that a new breakfast program improved student concentration, citing rising test scores in schools that adopted it. Which finding, if true, would most directly weaken the researcher''s argument?',
   jsonb_build_array('Schools that adopted the program also reduced class sizes that same year.','Some students in the program still skip breakfast occasionally.','Test scores measure memory as well as concentration.','The program''s meals cost more than the earlier menu did.'),0,48,
   'A simultaneous change (smaller classes) offers an alternative explanation for the score gains.'),
  (v_test_id,'rw','rw2','hard','craft and structure',
   'In an essay about coral reefs, the author interrupts a description of bleaching events to recount how a single reef off the coast of Belize rebounded after local fishing limits were enacted. The author most likely includes the account of the Belize reef to ______',
   jsonb_build_array('offer evidence that targeted policy can help reefs recover.','suggest that bleaching is less serious than scientists claim.','argue that fishing has no effect on reef health.','describe the economic value of Caribbean tourism.'),0,49,
   'The recovery after fishing limits shows that policy action can produce recovery, balancing the bleak description.'),
  (v_test_id,'rw','rw2','hard','standard english conventions',
   'Among the artifacts recovered from the shipwreck ______ a bronze astrolabe, an instrument sailors once used to navigate by the stars. Which choice completes the text so that it conforms to the conventions of Standard English?',
   jsonb_build_array('were','was','are being','have been'),1,50,
   'The inverted subject is the singular "astrolabe," so the singular verb "was" is required.'),
  (v_test_id,'rw','rw2','hard','craft and structure',
   'The committee remained ______ about the merger, praising its financial logic while worrying openly about the layoffs it would cause. Which choice completes the text with the most logical and precise word or phrase?',
   jsonb_build_array('ambivalent','enthusiastic','indifferent','hostile'),0,51,
   'Holding both praise and worry at once is mixed feeling, or "ambivalence."'),
  (v_test_id,'rw','rw2','hard','expression of ideas',
   'A student has taken these notes on the mathematician Katherine Johnson: Johnson calculated flight trajectories for NASA''s Mercury missions. In 1962, John Glenn asked her to verify computer-generated orbital calculations by hand. Glenn refused to fly until Johnson confirmed the numbers. The student wants to emphasize the trust an astronaut placed in Johnson''s work. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
   jsonb_build_array('Katherine Johnson calculated flight trajectories for NASA''s Mercury missions.','In 1962, John Glenn refused to fly until Johnson had personally verified the computer''s orbital calculations by hand.','NASA used computers to generate orbital calculations in 1962.','John Glenn flew a Mercury mission in 1962.'),1,52,
   'Glenn''s refusal to fly without her confirmation directly demonstrates his trust in Johnson.'),
  (v_test_id,'rw','rw2','hard','expression of ideas',
   'The manuscript was dismissed for decades as a clumsy forgery. ______ chemical analysis of its ink has now dated it firmly to the twelfth century. Which choice completes the text with the most logical transition?',
   jsonb_build_array('Similarly,','In fact,','Consequently,','For instance,'),1,53,
   '"In fact" introduces evidence that corrects the earlier dismissal.');

  -- ==============================================================
  -- MATH — MODULE 1 (22 questions, order 54-75)
  -- ==============================================================
  insert into public.questions (test_id, section, module_key, difficulty, topic, stem, choices, correct, order_num, explanation) values
  (v_test_id,'math','math1','easy','algebra',
   'If 3x + 5 = 20, what is the value of x?',
   jsonb_build_array('3','5','15','25/3'),1,54,
   'Subtract 5 from both sides to get 3x = 15, then divide by 3: x = 5.'),
  (v_test_id,'math','math1','easy','problem-solving and data analysis',
   'What is 15% of 240?',
   jsonb_build_array('24','30','36','40'),2,55,
   '0.15 x 240 = 36.'),
  (v_test_id,'math','math1','easy','problem-solving and data analysis',
   'What is the mean of the data set 4, 8, 9, 11?',
   jsonb_build_array('7','8','9','8.5'),1,56,
   'The sum is 32 and there are 4 values, so the mean is 32 / 4 = 8.'),
  (v_test_id,'math','math1','easy','algebra',
   'What is the slope of the line that passes through the points (1, 2) and (3, 8)?',
   jsonb_build_array('2','3','4','6'),1,57,
   'Slope = (8 - 2) / (3 - 1) = 6 / 2 = 3.'),
  (v_test_id,'math','math1','easy','advanced math',
   'If f(x) = 2x - 7, what is f(6)?',
   jsonb_build_array('-1','5','12','19'),1,58,
   'f(6) = 2(6) - 7 = 12 - 7 = 5.'),
  (v_test_id,'math','math1','easy','problem-solving and data analysis',
   'Two friends split 40 stickers in the ratio 3:5. How many stickers does the friend with the larger share receive?',
   jsonb_build_array('15','24','25','32'),2,59,
   'The ratio has 8 parts, so each part is 5 stickers; the larger share is 5 x 5 = 25.'),
  (v_test_id,'math','math1','easy','geometry and trigonometry',
   'A rectangle has a length of 8 centimeters and a width of 5 centimeters. What is its area, in square centimeters?',
   jsonb_build_array('13','26','40','80'),2,60,
   'Area = length x width = 8 x 5 = 40.'),
  (v_test_id,'math','math1','medium','algebra',
   'If x + y = 10 and x - y = 4, what is the value of x?',
   jsonb_build_array('3','6','7','14'),2,61,
   'Adding the equations gives 2x = 14, so x = 7.'),
  (v_test_id,'math','math1','medium','problem-solving and data analysis',
   'After a 20% discount, a jacket costs $48. What was the original price of the jacket?',
   jsonb_build_array('$57.60','$60','$68','$96'),1,62,
   'The sale price is 80% of the original: 48 / 0.8 = 60.'),
  (v_test_id,'math','math1','medium','problem-solving and data analysis',
   'What is the median of the data set 3, 7, 7, 9, 12, 15?',
   jsonb_build_array('7','8','9','7.5'),1,63,
   'With six values, the median is the average of the 3rd and 4th values: (7 + 9) / 2 = 8.'),
  (v_test_id,'math','math1','medium','algebra',
   'If 2(x - 3) = 5x + 9, what is the value of x?',
   jsonb_build_array('-5','-1','1','5'),0,64,
   '2x - 6 = 5x + 9, so -15 = 3x and x = -5.'),
  (v_test_id,'math','math1','medium','geometry and trigonometry',
   'A circle has an area of 36 pi square units. What is its circumference, in units?',
   jsonb_build_array('6 pi','12 pi','18 pi','36 pi'),1,65,
   'Area pi r^2 = 36 pi gives r = 6, so circumference = 2 pi r = 12 pi.'),
  (v_test_id,'math','math1','medium','advanced math',
   'Which expression is equivalent to (x^3)^2 * x ?',
   jsonb_build_array('x^6','x^7','x^8','x^9'),1,66,
   '(x^3)^2 = x^6, and x^6 * x = x^7.'),
  (v_test_id,'math','math1','medium','problem-solving and data analysis',
   'A bag contains 5 red marbles and 3 blue marbles. If one marble is drawn at random, what is the probability that it is blue?',
   jsonb_build_array('3/8','3/5','5/8','1/3'),0,67,
   'There are 3 blue marbles out of 8 total, so the probability is 3/8.'),
  (v_test_id,'math','math1','medium','algebra',
   'The total cost c, in dollars, of a rideshare trip is given by c = 2.50 + 1.20m, where m is the trip length in miles. What is the best interpretation of 1.20 in this context?',
   jsonb_build_array('The cost of each additional mile of the trip','The base fee charged for any trip','The total cost of a one-mile trip','The number of miles that can be traveled per dollar'),0,68,
   '1.20 multiplies the miles m, so it is the rate charged per mile; 2.50 is the base fee.'),
  (v_test_id,'math','math1','hard','advanced math',
   'What is the sum of the solutions to the equation x^2 - 5x + 6 = 0?',
   jsonb_build_array('-5','2','3','5'),3,69,
   'The equation factors as (x - 2)(x - 3) = 0, so the solutions are 2 and 3, and their sum is 5.'),
  (v_test_id,'math','math1','hard','advanced math',
   'The graph of g(x) = f(x - 2) + 3 is the graph of f shifted',
   jsonb_build_array('2 units left and 3 units down','2 units right and 3 units up','3 units right and 2 units up','2 units right and 3 units down'),1,70,
   'Replacing x with x - 2 shifts the graph right 2; adding 3 shifts it up 3.'),
  (v_test_id,'math','math1','hard','geometry and trigonometry',
   'A right triangle has legs of length 9 and 12. What is the length of its hypotenuse?',
   jsonb_build_array('13','15','17','21'),1,71,
   '9^2 + 12^2 = 81 + 144 = 225, and the square root of 225 is 15.'),
  (v_test_id,'math','math1','hard','advanced math',
   'A bacteria population starts at 800 and doubles every 5 hours. What is the population after 15 hours?',
   jsonb_build_array('2,400','3,200','4,800','6,400'),3,72,
   '15 hours contains three doubling periods: 800 x 2^3 = 6,400.'),
  (v_test_id,'math','math1','hard','algebra',
   'In the system 2x + 3y = 7 and 4x + 6y = k, for what value of k does the system have infinitely many solutions?',
   jsonb_build_array('7','10','14','28'),2,73,
   'The second equation is exactly twice the first when k = 2 x 7 = 14, making the equations identical.'),
  (v_test_id,'math','math1','hard','problem-solving and data analysis',
   'A stock''s price increased by 20% in one year and then decreased by 20% the following year. The final price is what percent of the original price?',
   jsonb_build_array('96%','100%','104%','98%'),0,74,
   '1.20 x 0.80 = 0.96, so the final price is 96% of the original.'),
  (v_test_id,'math','math1','hard','algebra',
   'Which of the following gives all solutions of the inequality |2x - 1| < 7?',
   jsonb_build_array('-3 < x < 4','-4 < x < 3','x < -3 or x > 4','-7 < x < 7'),0,75,
   '-7 < 2x - 1 < 7 gives -6 < 2x < 8, so -3 < x < 4.');

  -- ==============================================================
  -- MATH — MODULE 2 (22 questions, order 76-97)
  -- ==============================================================
  insert into public.questions (test_id, section, module_key, difficulty, topic, stem, choices, correct, order_num, explanation) values
  (v_test_id,'math','math2','easy','algebra',
   'If 5x - 4 = 21, what is the value of x?',
   jsonb_build_array('3','4','5','6'),2,76,
   'Add 4 to both sides: 5x = 25, so x = 5.'),
  (v_test_id,'math','math2','easy','problem-solving and data analysis',
   'How many minutes are in 2.5 hours?',
   jsonb_build_array('125','140','150','250'),2,77,
   '2.5 x 60 = 150 minutes.'),
  (v_test_id,'math','math2','easy','algebra',
   'What is the y-intercept of the graph of y = 4x - 9?',
   jsonb_build_array('(0, 4)','(0, -9)','(4, 0)','(-9, 0)'),1,78,
   'When x = 0, y = -9, so the graph crosses the y-axis at (0, -9).'),
  (v_test_id,'math','math2','easy','problem-solving and data analysis',
   'A train travels 180 miles in 3 hours at a constant speed. What is its speed, in miles per hour?',
   jsonb_build_array('45','54','60','90'),2,79,
   'Speed = distance / time = 180 / 3 = 60 miles per hour.'),
  (v_test_id,'math','math2','easy','advanced math',
   'What is the value of 3x^2 when x = -2?',
   jsonb_build_array('-12','-6','6','12'),3,80,
   '(-2)^2 = 4, and 3 x 4 = 12.'),
  (v_test_id,'math','math2','easy','problem-solving and data analysis',
   'If 5/8 = x/40, what is the value of x?',
   jsonb_build_array('8','20','25','32'),2,81,
   'Multiply both sides by 40: x = 5 x 40 / 8 = 25.'),
  (v_test_id,'math','math2','easy','geometry and trigonometry',
   'A square has an area of 49 square inches. What is its perimeter, in inches?',
   jsonb_build_array('14','21','28','49'),2,82,
   'Each side is 7 inches (since 7^2 = 49), so the perimeter is 4 x 7 = 28.'),
  (v_test_id,'math','math2','medium','problem-solving and data analysis',
   'A line of best fit for a scatterplot of study hours (x) and quiz scores (y) is y = 4.5x + 62. Which is the best interpretation of the slope of this line?',
   jsonb_build_array('Each additional hour of study is associated with a predicted increase of 4.5 points in quiz score.','A student who studies 0 hours is predicted to score 4.5 points.','Each additional point on the quiz is associated with 4.5 more hours of study.','The maximum possible quiz score is 62 plus 4.5 points.'),0,83,
   'The slope gives the predicted change in y (score) for each one-unit increase in x (hours).'),
  (v_test_id,'math','math2','medium','algebra',
   'If y = 2x and x + y = 12, what is the value of y?',
   jsonb_build_array('4','6','8','10'),2,84,
   'Substituting gives x + 2x = 12, so x = 4 and y = 2 x 4 = 8.'),
  (v_test_id,'math','math2','medium','problem-solving and data analysis',
   'A class of 20 students has an average score of 80, and another class of 30 students has an average score of 90. What is the average score of all 50 students?',
   jsonb_build_array('84','85','86','87'),2,85,
   'Total points = 20 x 80 + 30 x 90 = 1,600 + 2,700 = 4,300; 4,300 / 50 = 86.'),
  (v_test_id,'math','math2','medium','advanced math',
   'Which expression is equivalent to (x + 3)(x - 5)?',
   jsonb_build_array('x^2 - 2x - 15','x^2 + 2x - 15','x^2 - 15x - 2','x^2 - 8x + 15'),0,86,
   'FOIL: x^2 - 5x + 3x - 15 = x^2 - 2x - 15.'),
  (v_test_id,'math','math2','medium','advanced math',
   'If the square root of (x + 7) equals 4, what is the value of x?',
   jsonb_build_array('3','9','23','65'),1,87,
   'Squaring both sides gives x + 7 = 16, so x = 9.'),
  (v_test_id,'math','math2','medium','geometry and trigonometry',
   'Two parallel lines are cut by a transversal. One of the angles formed measures 65 degrees. What is the measure of its same-side interior angle?',
   jsonb_build_array('25 degrees','65 degrees','115 degrees','125 degrees'),2,88,
   'Same-side interior angles are supplementary: 180 - 65 = 115 degrees.'),
  (v_test_id,'math','math2','medium','problem-solving and data analysis',
   '45 is what percent of 180?',
   jsonb_build_array('20%','25%','40%','75%'),1,89,
   '45 / 180 = 0.25 = 25%.'),
  (v_test_id,'math','math2','medium','advanced math',
   'What are the zeros of the function f(x) = (x + 4)(x - 1)?',
   jsonb_build_array('x = 4 and x = -1','x = -4 and x = 1','x = -4 and x = -1','x = 4 and x = 1'),1,90,
   'Each factor equals zero when x = -4 or x = 1.'),
  (v_test_id,'math','math2','hard','advanced math',
   'What is the vertex of the parabola y = (x - 3)^2 + 2?',
   jsonb_build_array('(-3, 2)','(3, 2)','(3, -2)','(2, 3)'),1,91,
   'Vertex form y = (x - h)^2 + k has vertex (h, k) = (3, 2).'),
  (v_test_id,'math','math2','hard','geometry and trigonometry',
   'The equation x^2 + y^2 - 6x + 4y - 12 = 0 defines a circle in the xy-plane. What is the radius of the circle?',
   jsonb_build_array('4','5','6','25'),1,92,
   'Completing the square gives (x - 3)^2 + (y + 2)^2 = 25, so the radius is 5.'),
  (v_test_id,'math','math2','hard','geometry and trigonometry',
   'In a right triangle, the sine of acute angle A is 3/5. What is the cosine of angle A?',
   jsonb_build_array('3/4','4/5','5/4','2/5'),1,93,
   'With opposite 3 and hypotenuse 5, the adjacent side is 4 (3-4-5 triangle), so cos A = 4/5.'),
  (v_test_id,'math','math2','hard','advanced math',
   'A machine''s value halves every 4 years. If it is worth $1,600 today, what will it be worth in 12 years?',
   jsonb_build_array('$100','$200','$400','$533'),1,94,
   '12 years contains three halving periods: 1,600 x (1/2)^3 = 200.'),
  (v_test_id,'math','math2','hard','algebra',
   'Three pencils and two pens cost $4.70. One pencil and one pen together cost $2.00. What is the cost of one pen?',
   jsonb_build_array('$0.70','$1.10','$1.30','$1.50'),2,95,
   'From p + q = 2, p = 2 - q; then 3(2 - q) + 2q = 4.70 gives q = 1.30.'),
  (v_test_id,'math','math2','hard','advanced math',
   'If 6 / (x - 2) = 3, what is the value of x?',
   jsonb_build_array('0','2','4','6'),2,96,
   'Multiplying both sides by (x - 2) gives 6 = 3x - 6, so x = 4.'),
  (v_test_id,'math','math2','hard','geometry and trigonometry',
   'Two triangles are similar with a scale factor of 1.5. If the shortest side of the smaller triangle is 8, what is the length of the shortest side of the larger triangle?',
   jsonb_build_array('10','12','16','18'),1,97,
   'Corresponding sides scale by the factor: 8 x 1.5 = 12.');

  -- ---- Assign the test to every existing student ----
  insert into public.test_assignments (test_id, student_id)
  select v_test_id, p.id
  from public.profiles p
  where p.role = 'student'
  on conflict (test_id, student_id) do nothing;

  raise notice 'Created SAT Practice Test A (%) with 98 questions and assigned it to all students.', v_test_id;
end $$;
